### ISSUE TITLE
Hash table of floats increasing by 0.5?

### ISSUE THREAD

**Issue by kpu** [bitextor/pdf-extract#13]
I'm really struggling to understand what is going on here and how a hash table with floating-point font sizes as keys is useful, especially considering numerical precision fun.  

https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L1427

Also, it's spelled `font`

**Comment by dionwiggins** [comment]
The purpose of this feature is to normalize fonts across a pair of pages so that they are similar (i.e. H1, H2, H3, etc.) for use in sentence alignment. The fonts are collected here for matching and normalizing together and includes the various font properties. For example (font-family:CAAAAA+DejaVuSans-Bold;font-size:12.46pt;font-weight:bold;) would become H1.
This normalization makes it possible to match various headers to each other which may be in different fonts in different languages. By normalizing to H# format, these numbers may be useful. This has been changed to a variable so that it can be configured.  Typo in variable name also corrected.
